version: "2"
services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://db:3306"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 40s
  server:
    build: ./server
    volumes:
      - /app
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - DBHOST=db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 20s
    command: ["npm", "run", "start:prod"]
    depends_on:
      db:
        condition: service_healthy
  client:
    build: ./client
    volumes:
      - /app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    networks:
      - my-network
    environment:
      - HOST=server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://client:3000"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 20s
    depends_on:
      server:
        condition: service_started

networks:
  my-network:
    driver: bridge
