version: "3"
services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    networks:
      - my-network
  server:
    build: ./server
    volumes:
      - /app
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - DBHOST=db
    command:
      ["./wait-for-it.sh", "-s", "db:3306", "--", "npm", "run", "start:prod"]
    depends_on:
      - db
  client:
    build: ./client
    volumes:
      - /app
    ports:
      - "3000:3000"
    command: ["./wait-for-it.sh", "-s", "server:8080", "--", "./start.sh"]
    networks:
      - my-network
    environment:
      - HOST=server
    depends_on:
      - server
networks:
  my-network:
    driver: bridge
