version: "2"
services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    networks:
      - my-network
  server:
    build: ./server
    volumes:
      - /app
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - DBHOST=db
    command: ["npm", "run", "start:prod"]
    depends_on:
      db:
        condition: service_started
  client:
    build: ./client
    volumes:
      - /app
    ports:
      - "3000:3000"
    command: ["./start.sh"]
    networks:
      - my-network
    environment:
      - HOST=server
    depends_on:
      server:
        condition: service_started

networks:
  my-network:
    driver: bridge
