name: Deploy

on:
  push:
    branches:
      - master

jobs:
  # build:
  # name: Build and Test
  # runs-on: ubuntu-latest

  # steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Set up Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'

  #   - name: Test server
  #     run: |
  #       cd server
  #       npm i
  #       npm run test
  #       npm run test:e2e

  #   - name: Test client
  #     run: |
  #       cd client
  #       npm i
  #       npm run test
  #       npm run test:e2e

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest

    # needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build db Docker image
        run: |
          cd db
          sudo docker build -t db-mysql .

      - name: Run Docker container
        run: docker run -d -p 3306:3306 db-mysql

      - name: Build
        run: |
          cd server
          npm install
          npm run build
          npm run start & 
          cd ../client
          npm install
          npm run build

      - name: clear directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_PRIVATE_KEY }}
          script: |
            rm -rf /home/ubuntu/auto-deploy-test/client/.next/*
            rm -rf /home/ubuntu/auto-deploy-test/server/dist/*

      - name: Copy Server files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_PRIVATE_KEY }}
          source: "server/dist/*"
          target: "/home/ubuntu/auto-deploy-test/server/dist/"

      - name: Copy Client files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_PRIVATE_KEY }}
          source: "client/.next/*"
          target: "/home/ubuntu/auto-deploy-test/client/.next/"

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_PRIVATE_KEY }}
          script: |
            pm2 kill
            cd /home/ubuntu/auto-deploy-test/server
            pm2 start --name server -- npm run start
            cd ../client
            pm2 start --name client -- npm run start
            sudo service nginx restart
